---
version: 2
updates:
    # --- NPM / PNPM Configurations ---
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      commit-message:
          prefix: 'deps'
          include: 'scope'
      labels:
          - 'dependencies'
          - 'pnpm'
      groups:
          production-deps:
              dependency-type: 'production'
          development-deps:
              dependency-type: 'development'
